"""add_profile_readiness

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-18 20:48:44.059144
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

profile_readiness = postgresql.ENUM(
    'uploaded', 'needs_review', 'ready', 'parse_failed',
    name='profile_readiness', create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    profile_readiness.create(op.get_bind(), checkfirst=True)
    op.add_column('profile_facts', sa.Column('source_document_id', sa.UUID(), nullable=False))
    op.add_column('profile_facts', sa.Column('supersedes_fact_id', sa.UUID(), nullable=True))
    op.add_column('profile_facts', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('profile_facts', sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('profile_facts', sa.Column('element_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('profile_facts', sa.Column('correction_version', sa.Integer(), nullable=False))
    op.add_column('profile_facts', sa.Column('is_current', sa.Boolean(), nullable=False))
    op.create_foreign_key('fk_profile_facts_supersedes', 'profile_facts', 'profile_facts', ['supersedes_fact_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_profile_facts_source_document', 'profile_facts', 'source_documents', ['source_document_id'], ['id'], ondelete='CASCADE')
    op.add_column('profiles', sa.Column('readiness', profile_readiness, server_default='uploaded', nullable=False))
    op.add_column('profiles', sa.Column('source_comparison_resolved', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'source_comparison_resolved')
    op.drop_column('profiles', 'readiness')
    op.drop_constraint('fk_profile_facts_source_document', 'profile_facts', type_='foreignkey')
    op.drop_constraint('fk_profile_facts_supersedes', 'profile_facts', type_='foreignkey')
    op.drop_column('profile_facts', 'is_current')
    op.drop_column('profile_facts', 'correction_version')
    op.drop_column('profile_facts', 'element_ids')
    op.drop_column('profile_facts', 'bounding_box')
    op.drop_column('profile_facts', 'page_number')
    op.drop_column('profile_facts', 'supersedes_fact_id')
    op.drop_column('profile_facts', 'source_document_id')
    profile_readiness.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
