"""widen_job_posting_columns

Revision ID: 0005
Revises: 0004
Create Date: 2026-07-20 21:47:57.151749
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_postings', 'company',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('job_postings', 'title',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('job_postings', 'team',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('job_postings', 'location',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('job_postings', 'commitment',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_postings', 'commitment',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('job_postings', 'location',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('job_postings', 'team',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('job_postings', 'title',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    op.alter_column('job_postings', 'company',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###
