"""add_document_change_operation_classification

Revision ID: 0006
Revises: 0005
Create Date: 2026-07-20 22:43:27.415518
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_changes', sa.Column('operation', sa.String(length=20), nullable=False))
    op.add_column('document_changes', sa.Column('classification', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_changes', 'classification')
    op.drop_column('document_changes', 'operation')
    # ### end Alembic commands ###
